# -*- coding: utf-8 -*-
"""P1_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p0NnzCnPslLH9US8geK7PCv4dwXMbFYu
"""

direction =[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]
target = False
start = list(map(int,input().split()))
destination = list(map(int,input().split()))
for i in direction:
  if([destination[0] - start[0],destination[1] - start[1]] == i ):
      if(checkerboard[destination[0]][destination[1]]==0):
        target = True
        print("Yes")
if(not target):
  print("No")